server:
  port: 8082

spring:
  application:
    name: API-GATEWAY-SERVICE1

  

  cloud:
    gateway:
      routes:
        - id: CASE-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cases/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
